apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo-gitrepository
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
